name: IndexNow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  indexnow:
    runs-on: ubuntu-latest
    steps:
      - name: IndexNow Action
        uses: bojan88/indexnow-action@v2
        with:
          sitemap-location: 'https://bantukamituhan.github.io/id/sitemap.xml'
          key: '8572b9a7c6d44e80823719274028681d'
